name = "aquarius"
description = "An EBNF compiler"
version = "0.1.0-dev"

authors = ["Fraser Wilson"]
maintainers = ["Fraser Wilson <fraser@thewhitelion.eu>"]
maintainers-logins = ["blancolioni"]
licenses = "GPL-3.0-or-later"
website = ""
tags = ["editor", "compiler", "ebnf", "parser"]

executables = ["aquarius-driver"]

[build-profiles]
"*" = "development"

[[depends-on]]
tagatha = "*"
aqua_vm = "*"
aquarius_base = "*"
aquarius_ack = "*"
aquarius_io = "*"
aquarius_plugins = "*"
aquarius_trees = "*"
aquarius_syntax = "*"
aquarius_programs = "*"

[[pins]]
tagatha = { path = "../tagatha" }
aqua_vm = { path = "../aqua/aqua_vm" }
aquarius_base = { path = "./aquarius_base" }
aquarius_ack = { path = "./aquarius_ack" }
aquarius_io = { path = "./aquarius_io" }
aquarius_plugins = { path = "./aquarius_plugins" }
aquarius_trees = { path = "./aquarius_trees" }
aquarius_syntax = { path = "./aquarius_syntax" }
aquarius_programs = { path = "./aquarius_programs" }

[build-switches]
"*".ada_version = "ada2022"
Development.Runtime_Checks = "Everything"
"*".Style_Checks = "yes"
development.contracts = "yes"
"*".compile_checks = "errors"

[[depends-on]]
parse_args = "~0.9.0"
