name = "aquarius_test"
description = "Aquarius internal unit-test suite"
version = "0.1.0-dev"

authors = ["Fraser Wilson"]
maintainers = ["Fraser Wilson <fraser@thewhitelion.eu>"]
maintainers-logins = ["blancolioni"]
licenses = "GPL-3.0-or-later"
website = ""
tags = []

executables = ["tests"]

[build-profiles]
"*" = "development"

[[depends-on]]
aquarius_library = "*"
aquarius_ui = "*"
wl_lib = "*"

[[pins]]
aquarius_library = { path = "../aquarius_library" }
aquarius_ui = { path = "../aquarius_ui" }
wl_lib = { path = "../wl_lib" }

[build-switches]
"*".ada_version = "ada2022"
Development.Runtime_Checks = "Everything"
"*".Style_Checks = "yes"
development.contracts = "yes"
"*".compile_checks = "errors"
