name = "aquarius_syntax"
description = "Syntax trees for Aquarius"
version = "0.1.0-dev"

authors = ["Fraser Wilson"]
maintainers = ["Fraser Wilson <fraser@thewhitelion.eu>"]
maintainers-logins = ["blancolioni"]
licenses = "GPL-3.0-or-later"
website = ""
tags = []

[[depends-on]]
aquarius_base = "*"
aquarius_trees = "*"

[[pins]]
aquarius_base = { path = "../aquarius_base" }
aquarius_trees = { path = "../aquarius_trees" }

[build-switches]
"*".ada_version = "ada2022"
Development.Runtime_Checks = "Everything"
"*".Style_Checks = "yes"
development.contracts = "yes"
"*".compile_checks = "errors"
