name = "aquarius_plugins"
description = "Aquarius plugin system"
version = "0.1.0-dev"

authors = ["Fraser Wilson"]
maintainers = ["Fraser Wilson <fraser@thewhitelion.eu>"]
maintainers-logins = ["blancolioni"]
licenses = "GPL-3.0-or-later"
website = ""
tags = []

[[depends-on]]
aqua_vm = "*"
aquarius_base = "*"
aquarius_ack = "*"
aquarius_io = "*"
aquarius_programs = "*"
aquarius_syntax = "*"
aquarius_trees = "*"

[[pins]]
aqua_vm = { path = "../aqua_vm" }
aquarius_base = { path = "../aquarius_base" }
aquarius_ack = { path = "../aquarius_ack" }
aquarius_io = { path = "../aquarius_io" }
aquarius_programs = { path = "../aquarius_programs" }
aquarius_syntax = { path = "../aquarius_syntax" }
aquarius_trees = { path = "../aquarius_trees" }

[build-switches]
"*".ada_version = "ada2022"
Development.Runtime_Checks = "Everything"
"*".Style_Checks = "yes"
development.contracts = "yes"
"*".compile_checks = "errors"
