name = "aquarius_base"
description = "Base Aquarius packages"
version = "0.1.0-dev"

authors = ["Fraser Wilson"]
maintainers = ["Fraser Wilson <fraser@thewhitelion.eu>"]
maintainers-logins = ["blancolioni"]
licenses = "GPL-3.0-or-later"
website = ""
tags = []

[[depends-on]]
kosei = "*"

[[pins]]
kosei = { path = "../kosei" }

[build-switches]
"*".ada_version = "ada2022"
Development.Runtime_Checks = "Everything"
"*".Style_Checks = "yes"
development.contracts = "yes"
"*".compile_checks = "errors"

[[depends-on]]
parse_args = "~0.9.0"
