name: Ada (GNAT)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Aqua VM
      uses: actions/checkout@v4
      with:
        repository: blancolioni/aqua_vm
        path: .
        
    - name: Checkout Aqua Assembler
      uses: actions/checkout@v4
      with:
        repository: blancolioni/aqua_as
        path: .
        
    - name: Checkout Tagatha
      uses: actions/checkout@v4
      with:
        repository: blancolioni/tagatha
        path: .
        
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up alire
      uses: alire-project/setup-alire@v2

    - name: Build      
      run: alr build
      
